baseURL = 'https://railatlas.app/'
languageCode = 'en-us'
title = 'RailAtlas'

[module]
    [[module.imports]]
        path = "github.com/colinwilson/lotusdocs"
        disable = false
    [[module.imports]]
        path = "github.com/gohugoio/hugo-mod-bootstrap-scss/v5"
        disable = false

[params.HugoShortcodes.GooglePlay]
    App = 'com.chess'
    Lang = 'en'
    Alt = 'Get it on Google Play'
    Width = '200'